packages:
  - packages/*
  - docs-site
  - .

catalog:
  "@docusaurus/core": "3.4.0"
  "@docusaurus/module-type-aliases": "3.4.0"
  "@docusaurus/preset-classic": "3.4.0"
  "@docusaurus/theme-classic": "3.4.0"
  "@docusaurus/tsconfig": "3.4.0"
  "@docusaurus/types": "3.4.0"
  "@mdx-js/react": "^3.0.0"
  "@nx-dotnet/nx-ghpages": "^2.3.0"
  "@nx/devkit": "22.5.0"
  "@nx/js": "22.5.0"
  "@swc-node/register": "1.11.1"
  "@swc/core": "1.15.8"
  "@swc/helpers": "0.5.18"
  "@types/cli-progress": "^3.11.6"
  "@types/is-ci": "^3.0.4"
  "@types/node": "^20.14.10"
  cli-forge: "^1.2.0"
  cli-progress: "^3.12.0"
  clsx: "^2.0.0"
  docusaurus-plugin-typedoc: "^1.4.2"
  is-ci: "^4.1.0"
  markdown-factory: "^0.0.6"
  nx: "22.5.0"
  patch-package: "^8.0.0"
  prettier: "^3.3.2"
  prism-react-renderer: "^2.3.0"
  react: "^18.0.0"
  react-dom: "^18.0.0"
  remark-github: "^12.0.0"
  ts-node: "^10.9.2"
  tsx: "^4.16.2"
  typedoc: "^0.28.16"
  typedoc-plugin-markdown: "^4.10.0"
  typescript: "^5.5.3"
  vitest: "^4.0.18"
  yaml: "^2.4.5"
